<?php

declare(strict_types=1);

namespace Nexus\Export;

use Nexus\Models\Document;
use Nexus\Models\DocumentCluster;
use Nexus\Utils\Exceptions\ExportError;

class BibtexExporter extends BaseExporter
{
    private array $usedKeys = [];

    public function getFileExtension(): string
    {
        return 'bib';
    }

    public function exportDocuments(array $documents, string $outputFile, ...$kwargs): string
    {
        $filename = $this->ensureExtension($outputFile, $this->getFileExtension());
        $path = $this->getOutputPath($filename);

        $maxAbstractLength = $kwargs['max_abstract_length'] ?? null;
        $this->usedKeys = [];

        try {
            $content = "% BibTeX entries generated by Nexus Scout\n\n";

            foreach ($documents as $doc) {
                $content .= $this->documentToBibtex($doc, $maxAbstractLength) . "\n\n";
            }

            $this->writeToFile($path, $content);
        } catch (\Throwable $e) {
            throw new ExportError("Failed to write BibTeX file: {$e->getMessage()}", 'bib');
        }

        return $path;
    }

    public function exportClusters(array $clusters, string $outputFile, ...$kwargs): string
    {
        $representatives = array_map(
            fn(DocumentCluster $c) => $c->representative,
            $clusters
        );

        return $this->exportDocuments($representatives, $outputFile, ...$kwargs);
    }

    private function documentToBibtex(Document $doc, ?int $maxAbstractLength = null): string
    {
        $citeKey = $this->generateUniqueCiteKey($doc);
        $entryType = $this->determineEntryType($doc);

        $lines = ["@{$entryType}{{$citeKey},"];

        if ($doc->title) {
            $lines[] = "  title = {{" . $this->escapeLatex($doc->title) . "}},";
        }

        if (!empty($doc->authors)) {
            $authorStr = $this->formatAuthorsBibtex($doc->authors);
            $lines[] = "  author = {{$authorStr}},";
        }

        if ($doc->year) {
            $lines[] = "  year = {{$doc->year}},";
        }

        if ($doc->venue) {
            if ($entryType === 'article') {
                $lines[] = "  journal = {{" . $this->escapeLatex($doc->venue) . "}},";
            } elseif ($entryType === 'inproceedings') {
                $lines[] = "  booktitle = {{" . $this->escapeLatex($doc->venue) . "}},";
            } else {
                $lines[] = "  publisher = {{" . $this->escapeLatex($doc->venue) . "}},";
            }
        }

        if ($doc->abstract) {
            $abstract = $doc->abstract;
            if ($maxAbstractLength !== null && strlen($abstract) > $maxAbstractLength) {
                $abstract = substr($abstract, 0, $maxAbstractLength - 3) . '...';
            }
            $lines[] = "  abstract = {{" . $this->escapeLatex($abstract) . "}},";
        }

        if ($doc->externalIds->doi) {
            $lines[] = "  doi = {{$doc->externalIds->doi}},";
        }

        if ($doc->url) {
            $lines[] = "  url = {{$doc->url}},";
        } elseif ($doc->externalIds->doi) {
            $lines[] = "  url = {{https://doi.org/{$doc->externalIds->doi}}},";
        }

        if ($doc->externalIds->arxivId) {
            $lines[] = "  eprint = {{$doc->externalIds->arxivId}},";
            $lines[] = "  archivePrefix = {{arXiv}},";
        }

        $notes = [];
        if ($doc->provider) {
            $notes[] = "Source: {$doc->provider}";
        }
        if ($doc->citedByCount) {
            $notes[] = "Citations: {$doc->citedByCount}";
        }
        if (!empty($notes)) {
            $lines[] = "  note = {{" . implode(', ', $notes) . "}},";
        }

        if (str_ends_with(end($lines), ',')) {
            $lines[count($lines) - 1] = rtrim(end($lines), ',');
        }

        $lines[] = "}";

        return implode("\n", $lines);
    }

    private function generateUniqueCiteKey(Document $doc): string
    {
        $baseKey = $this->generateCiteKey($doc);

        if (!isset($this->usedKeys[$baseKey])) {
            $this->usedKeys[$baseKey] = true;
            return $baseKey;
        }

        $suffix = 'a';
        while (true) {
            $newKey = $baseKey . $suffix;
            if (!isset($this->usedKeys[$newKey])) {
                $this->usedKeys[$newKey] = true;
                return $newKey;
            }
            $suffix++;
        }
    }

    private function generateCiteKey(Document $doc): string
    {
        $parts = [];

        if (!empty($doc->authors) && $doc->authors[0]->familyName) {
            $name = preg_replace('/[^a-zA-Z]/', '', $doc->authors[0]->familyName);
            if ($name) {
                $parts[] = $name;
            }
        }

        if ($doc->year) {
            $parts[] = (string) $doc->year;
        }

        if ($doc->title) {
            $skipWords = ['a', 'an', 'the', 'on', 'in', 'at', 'of', 'for', 'to', 'and', 'or'];
            $words = preg_split('/\s+/', strtolower($doc->title));
            foreach ($words as $word) {
                $cleanWord = preg_replace('/[^a-z]/', '', $word);
                if ($cleanWord && !in_array($cleanWord, $skipWords) && strlen($cleanWord) > 2) {
                    $parts[] = ucfirst($cleanWord);
                    break;
                }
            }
        }

        if (empty($parts)) {
            if ($doc->providerId) {
                $cleanId = preg_replace('/[^a-zA-Z0-9]/', '', $doc->providerId);
                return substr($cleanId, 0, 20);
            }
            return 'UnknownRef';
        }

        $key = implode('', $parts);

        if (strlen($key) > 30) {
            $key = substr($key, 0, 30);
        }

        return $key;
    }

    private function determineEntryType(Document $doc): string
    {
        $venueLower = strtolower($doc->venue ?? '');

        $confKeywords = ['conference', 'proceedings', 'workshop', 'symposium', 'congress'];
        foreach ($confKeywords as $keyword) {
            if (str_contains($venueLower, $keyword)) {
                return 'inproceedings';
            }
        }

        $journalKeywords = ['journal', 'review', 'magazine', 'transactions'];
        foreach ($journalKeywords as $keyword) {
            if (str_contains($venueLower, $keyword)) {
                return 'article';
            }
        }

        if ($doc->provider === 'arxiv') {
            return 'misc';
        }

        if ($doc->externalIds->doi) {
            return 'article';
        }

        return 'misc';
    }

    private function formatAuthorsBibtex(array $authors): string
    {
        if (empty($authors)) {
            return '';
        }

        $authorStrs = [];
        foreach ($authors as $author) {
            if ($author->givenName) {
                $authorStrs[] = "{$author->givenName} {$author->familyName}";
            } else {
                $authorStrs[] = $author->familyName;
            }
        }

        return implode(' and ', $authorStrs);
    }

    private function escapeLatex(string $text): string
    {
        if (empty($text)) {
            return '';
        }

        $replacements = [
            '\\' => '\\textbackslash{}',
            '&' => '\\&',
            '%' => '\\%',
            '$' => '\\$',
            '#' => '\\#',
            '_' => '\\_',
            '{' => '\\{',
            '}' => '\\}',
            '~' => '\\textasciitilde{}',
            '^' => '\\textasciicircum{}',
        ];

        $result = $text;
        foreach ($replacements as $char => $replacement) {
            $result = str_replace($char, $replacement, $result);
        }

        return $result;
    }
}
